//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteEntidadBanco.WSBanco {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSBanco.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name XmlRecepcionPagoCpx from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestRecepcionPagoCPX", ReplyAction="*")]
        ClienteEntidadBanco.WSBanco.RequestRecepcionPagoCPXResponse RequestRecepcionPagoCPX(ClienteEntidadBanco.WSBanco.RequestRecepcionPagoCPXRequest request);
        
        // CODEGEN: Generating message contract since element name XmlDatosUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestCrearCuenta", ReplyAction="*")]
        ClienteEntidadBanco.WSBanco.RequestCrearCuentaResponse RequestCrearCuenta(ClienteEntidadBanco.WSBanco.RequestCrearCuentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestRecepcionPagoCPXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestRecepcionPagoCPX", Namespace="http://tempuri.org/", Order=0)]
        public ClienteEntidadBanco.WSBanco.RequestRecepcionPagoCPXRequestBody Body;
        
        public RequestRecepcionPagoCPXRequest() {
        }
        
        public RequestRecepcionPagoCPXRequest(ClienteEntidadBanco.WSBanco.RequestRecepcionPagoCPXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestRecepcionPagoCPXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlRecepcionPagoCpx;
        
        public RequestRecepcionPagoCPXRequestBody() {
        }
        
        public RequestRecepcionPagoCPXRequestBody(string XmlRecepcionPagoCpx) {
            this.XmlRecepcionPagoCpx = XmlRecepcionPagoCpx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestRecepcionPagoCPXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestRecepcionPagoCPXResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteEntidadBanco.WSBanco.RequestRecepcionPagoCPXResponseBody Body;
        
        public RequestRecepcionPagoCPXResponse() {
        }
        
        public RequestRecepcionPagoCPXResponse(ClienteEntidadBanco.WSBanco.RequestRecepcionPagoCPXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestRecepcionPagoCPXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestRecepcionPagoCPXResult;
        
        public RequestRecepcionPagoCPXResponseBody() {
        }
        
        public RequestRecepcionPagoCPXResponseBody(string RequestRecepcionPagoCPXResult) {
            this.RequestRecepcionPagoCPXResult = RequestRecepcionPagoCPXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestCrearCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestCrearCuenta", Namespace="http://tempuri.org/", Order=0)]
        public ClienteEntidadBanco.WSBanco.RequestCrearCuentaRequestBody Body;
        
        public RequestCrearCuentaRequest() {
        }
        
        public RequestCrearCuentaRequest(ClienteEntidadBanco.WSBanco.RequestCrearCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestCrearCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlDatosUsuario;
        
        public RequestCrearCuentaRequestBody() {
        }
        
        public RequestCrearCuentaRequestBody(string XmlDatosUsuario) {
            this.XmlDatosUsuario = XmlDatosUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestCrearCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestCrearCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteEntidadBanco.WSBanco.RequestCrearCuentaResponseBody Body;
        
        public RequestCrearCuentaResponse() {
        }
        
        public RequestCrearCuentaResponse(ClienteEntidadBanco.WSBanco.RequestCrearCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestCrearCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestCrearCuentaResult;
        
        public RequestCrearCuentaResponseBody() {
        }
        
        public RequestCrearCuentaResponseBody(string RequestCrearCuentaResult) {
            this.RequestCrearCuentaResult = RequestCrearCuentaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ClienteEntidadBanco.WSBanco.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ClienteEntidadBanco.WSBanco.ServiceSoap>, ClienteEntidadBanco.WSBanco.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteEntidadBanco.WSBanco.RequestRecepcionPagoCPXResponse ClienteEntidadBanco.WSBanco.ServiceSoap.RequestRecepcionPagoCPX(ClienteEntidadBanco.WSBanco.RequestRecepcionPagoCPXRequest request) {
            return base.Channel.RequestRecepcionPagoCPX(request);
        }
        
        public string RequestRecepcionPagoCPX(string XmlRecepcionPagoCpx) {
            ClienteEntidadBanco.WSBanco.RequestRecepcionPagoCPXRequest inValue = new ClienteEntidadBanco.WSBanco.RequestRecepcionPagoCPXRequest();
            inValue.Body = new ClienteEntidadBanco.WSBanco.RequestRecepcionPagoCPXRequestBody();
            inValue.Body.XmlRecepcionPagoCpx = XmlRecepcionPagoCpx;
            ClienteEntidadBanco.WSBanco.RequestRecepcionPagoCPXResponse retVal = ((ClienteEntidadBanco.WSBanco.ServiceSoap)(this)).RequestRecepcionPagoCPX(inValue);
            return retVal.Body.RequestRecepcionPagoCPXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteEntidadBanco.WSBanco.RequestCrearCuentaResponse ClienteEntidadBanco.WSBanco.ServiceSoap.RequestCrearCuenta(ClienteEntidadBanco.WSBanco.RequestCrearCuentaRequest request) {
            return base.Channel.RequestCrearCuenta(request);
        }
        
        public string RequestCrearCuenta(string XmlDatosUsuario) {
            ClienteEntidadBanco.WSBanco.RequestCrearCuentaRequest inValue = new ClienteEntidadBanco.WSBanco.RequestCrearCuentaRequest();
            inValue.Body = new ClienteEntidadBanco.WSBanco.RequestCrearCuentaRequestBody();
            inValue.Body.XmlDatosUsuario = XmlDatosUsuario;
            ClienteEntidadBanco.WSBanco.RequestCrearCuentaResponse retVal = ((ClienteEntidadBanco.WSBanco.ServiceSoap)(this)).RequestCrearCuenta(inValue);
            return retVal.Body.RequestCrearCuentaResult;
        }
    }
}
